#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.paths=/home/aviferdev/.jdks/corretto-21.0.8,/home/aviferdev/.jdks/corretto-22.0.2,/home/aviferdev/.gradle/jdks/jetbrains_s_r_o_-21-amd64-linux.2

#Kotlin Native
kotlin.native.ignoreDisabledTargets=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true